from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.improvement_suggestion import ImprovementSuggestion
    from ..models.metric_score import MetricScore
    from ..models.repository_info import RepositoryInfo


T = TypeVar("T", bound="RepositoryQualityResponse")


@_attrs_define
class RepositoryQualityResponse:
    """Response containing the full quality analysis.

    Attributes:
        repository_url (str):
        owner (str):
        name (str):
        overall_score (float): Weighted overall quality score.
        grade (str): Letter grade: A (90+), B (70-89), C (50-69), D (30-49), F (<30).
        metrics (list[MetricScore]): Individual metric scores with breakdown.
        summary (str): AI-generated summary of the repository quality.
        repository_info (RepositoryInfo): Basic metadata about the analyzed repository.
        suggestions (list[ImprovementSuggestion] | Unset): Actionable improvement suggestions generated by AI.
    """

    repository_url: str
    owner: str
    name: str
    overall_score: float
    grade: str
    metrics: list[MetricScore]
    summary: str
    repository_info: RepositoryInfo
    suggestions: list[ImprovementSuggestion] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        repository_url = self.repository_url

        owner = self.owner

        name = self.name

        overall_score = self.overall_score

        grade = self.grade

        metrics = []
        for metrics_item_data in self.metrics:
            metrics_item = metrics_item_data.to_dict()
            metrics.append(metrics_item)

        summary = self.summary

        repository_info = self.repository_info.to_dict()

        suggestions: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.suggestions, Unset):
            suggestions = []
            for suggestions_item_data in self.suggestions:
                suggestions_item = suggestions_item_data.to_dict()
                suggestions.append(suggestions_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "repository_url": repository_url,
                "owner": owner,
                "name": name,
                "overall_score": overall_score,
                "grade": grade,
                "metrics": metrics,
                "summary": summary,
                "repository_info": repository_info,
            }
        )
        if suggestions is not UNSET:
            field_dict["suggestions"] = suggestions

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.improvement_suggestion import ImprovementSuggestion
        from ..models.metric_score import MetricScore
        from ..models.repository_info import RepositoryInfo

        d = dict(src_dict)
        repository_url = d.pop("repository_url")

        owner = d.pop("owner")

        name = d.pop("name")

        overall_score = d.pop("overall_score")

        grade = d.pop("grade")

        metrics = []
        _metrics = d.pop("metrics")
        for metrics_item_data in _metrics:
            metrics_item = MetricScore.from_dict(metrics_item_data)

            metrics.append(metrics_item)

        summary = d.pop("summary")

        repository_info = RepositoryInfo.from_dict(d.pop("repository_info"))

        _suggestions = d.pop("suggestions", UNSET)
        suggestions: list[ImprovementSuggestion] | Unset = UNSET
        if _suggestions is not UNSET:
            suggestions = []
            for suggestions_item_data in _suggestions:
                suggestions_item = ImprovementSuggestion.from_dict(
                    suggestions_item_data
                )

                suggestions.append(suggestions_item)

        repository_quality_response = cls(
            repository_url=repository_url,
            owner=owner,
            name=name,
            overall_score=overall_score,
            grade=grade,
            metrics=metrics,
            summary=summary,
            repository_info=repository_info,
            suggestions=suggestions,
        )

        repository_quality_response.additional_properties = d
        return repository_quality_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
