"""Create user_skills table

Revision ID: 314aca846457
Revises: c7cf74b3cd54
Create Date: 2026-06-27 10:29:43.018808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "314aca846457"
down_revision: Union[str, Sequence[str], None] = "c7cf74b3cd54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("connected_by", sa.UUID(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum("GITHUB", "GITLAB", "BITBUCKET", name="repositoryprovider"),
            nullable=False,
        ),
        sa.Column("repository_id", sa.String(length=100), nullable=True),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_branch", sa.String(length=50), nullable=False),
        sa.Column("clone_url", sa.String(length=500), nullable=True),
        sa.Column("html_url", sa.String(length=500), nullable=False),
        sa.Column("homepage", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=100), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("forks", sa.Integer(), nullable=False),
        sa.Column("watchers", sa.Integer(), nullable=False),
        sa.Column("open_issues", sa.Integer(), nullable=False),
        sa.Column("contributors", sa.Integer(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("synced", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connected_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_index(
        op.f("ix_repositories_connected_by"),
        "repositories",
        ["connected_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repositories_project_id"), "repositories", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repositories_project_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_connected_by"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
