"""Create user_skills table

Revision ID: 3549d852f034
Revises: 5ee676686fd4
Create Date: 2026-06-27 10:21:22.618732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3549d852f034"
down_revision: Union[str, Sequence[str], None] = "5ee676686fd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "builder_flares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=150), nullable=True),
        sa.Column("commitment", sa.String(length=100), nullable=True),
        sa.Column("experience_level", sa.String(length=100), nullable=True),
        sa.Column("openings", sa.Integer(), nullable=False),
        sa.Column("applicants_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PAUSED", "CLOSED", name="flarestatus"),
            nullable=False,
        ),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_builder_flares_created_by"),
        "builder_flares",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_builder_flares_project_id"),
        "builder_flares",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_builder_flares_project_id"), table_name="builder_flares")
    op.drop_index(op.f("ix_builder_flares_created_by"), table_name="builder_flares")
    op.drop_table("builder_flares")
    # ### end Alembic commands ###
