"""Create user_skills table

Revision ID: 398267091e7b
Revises: 314aca846457
Create Date: 2026-06-27 10:31:30.332876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "398267091e7b"
down_revision: Union[str, Sequence[str], None] = "314aca846457"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("following_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["following_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "follower_id", "following_id", name="uq_follower_relationship"
        ),
    )
    op.create_index(
        op.f("ix_followers_follower_id"), "followers", ["follower_id"], unique=False
    )
    op.create_index(
        op.f("ix_followers_following_id"), "followers", ["following_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_followers_following_id"), table_name="followers")
    op.drop_index(op.f("ix_followers_follower_id"), table_name="followers")
    op.drop_table("followers")
    # ### end Alembic commands ###
