"""Create user_skills table

Revision ID: 399f256b6aa1
Revises: 942f8407220c
Create Date: 2026-06-27 10:18:58.972702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "399f256b6aa1"
down_revision: Union[str, Sequence[str], None] = "942f8407220c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("minimum_experience", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "skill_id", name="uq_project_skill"),
    )
    op.create_index(
        op.f("ix_project_skills_project_id"),
        "project_skills",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_skills_skill_id"), "project_skills", ["skill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_skills_skill_id"), table_name="project_skills")
    op.drop_index(op.f("ix_project_skills_project_id"), table_name="project_skills")
    op.drop_table("project_skills")
    # ### end Alembic commands ###
