"""Create audit_logs table

Revision ID: c14aa06f723a
Revises: 51602fc145b0
Create Date: 2026-06-27 10:39:26.423142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c14aa06f723a"
down_revision: Union[str, Sequence[str], None] = "51602fc145b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN",
                "LOGOUT",
                "REGISTER",
                "PASSWORD_CHANGED",
                "PASSWORD_RESET",
                "EMAIL_CHANGED",
                "PROFILE_UPDATED",
                "ACCOUNT_DELETED",
                "PROJECT_CREATED",
                "PROJECT_UPDATED",
                "PROJECT_DELETED",
                "BUILDER_FLARE_CREATED",
                "BUILDER_FLARE_UPDATED",
                "BUILDER_FLARE_DELETED",
                "APPLICATION_SUBMITTED",
                "APPLICATION_ACCEPTED",
                "APPLICATION_REJECTED",
                "REPOSITORY_CONNECTED",
                "REPOSITORY_SYNCED",
                "ORGANIZATION_CREATED",
                "ORGANIZATION_UPDATED",
                "ROLE_CHANGED",
                "USER_BANNED",
                "USER_UNBANNED",
                "FAILED_LOGIN",
                "TOKEN_REVOKED",
                "API_ACCESS",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_method", sa.String(length=10), nullable=True),
        sa.Column("request_path", sa.String(length=500), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
