"""Create user_skills table

Revision ID: ef74e1dfae4e
Revises: 79de7ba3ecfd
Create Date: 2026-06-27 10:24:57.273017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef74e1dfae4e"
down_revision: Union[str, Sequence[str], None] = "79de7ba3ecfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", name="conversationrole"),
            nullable=False,
        ),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "user_id", name="uq_conversation_member"
        ),
    )
    op.create_index(
        op.f("ix_conversation_members_conversation_id"),
        "conversation_members",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_members_user_id"),
        "conversation_members",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_members_user_id"), table_name="conversation_members"
    )
    op.drop_index(
        op.f("ix_conversation_members_conversation_id"),
        table_name="conversation_members",
    )
    op.drop_table("conversation_members")
    # ### end Alembic commands ###
