"""
Pydantic schemas for the AI Repository Quality Analyzer.
"""

from __future__ import annotations

from enum import Enum

# pyrefly: ignore [missing-import]
from pydantic import BaseModel, Field


class QualityMetric(str, Enum):
    """Individual quality metrics that can be scored."""

    README = "readme"
    DOCUMENTATION = "documentation"
    LICENSE = "license"
    TEST_COVERAGE = "test_coverage"
    CI_CD = "ci_cd"
    RECENT_ACTIVITY = "recent_activity"
    OPEN_ISSUES = "open_issues"


class MetricScore(BaseModel):
    """Score and details for a single quality metric."""

    metric: QualityMetric
    score: float = Field(
        ..., ge=0.0, le=1.0, description="Score from 0.0 (worst) to 1.0 (best)."
    )
    label: str = Field(..., description="Human-readable metric name.")
    description: str = Field(
        ..., description="Explanation of how this score was computed."
    )
    weight: float = Field(
        ..., description="Weight of this metric in the overall score."
    )


class ImprovementSuggestion(BaseModel):
    """A single actionable improvement suggestion."""

    priority: str = Field(
        ..., description="Priority level: 'high', 'medium', or 'low'."
    )
    category: QualityMetric = Field(
        ..., description="Which metric this suggestion addresses."
    )
    title: str = Field(..., description="Short title of the suggestion.")
    description: str = Field(
        ..., description="Detailed explanation of the improvement."
    )


class RepositoryQualityRequest(BaseModel):
    """Request body for repository quality analysis."""

    repository_url: str = Field(
        ...,
        description="GitHub repository URL (e.g. https://github.com/owner/repo).",
        examples=["https://github.com/facebook/react"],
    )


class RepositoryQualityResponse(BaseModel):
    """Response containing the full quality analysis."""

    repository_url: str
    owner: str
    name: str
    overall_score: float = Field(
        ..., ge=0.0, le=1.0, description="Weighted overall quality score."
    )
    grade: str = Field(
        ...,
        description="Letter grade: A (90+), B (70-89), C (50-69), D (30-49), F (<30).",
    )
    metrics: list[MetricScore] = Field(
        ..., description="Individual metric scores with breakdown."
    )
    suggestions: list[ImprovementSuggestion] = Field(
        default_factory=list,
        description="Actionable improvement suggestions generated by AI.",
    )
    summary: str = Field(
        ..., description="AI-generated summary of the repository quality."
    )
    repository_info: RepositoryInfo = Field(
        ..., description="Basic repository metadata."
    )


class RepositoryInfo(BaseModel):
    """Basic metadata about the analyzed repository."""

    stars: int = 0
    forks: int = 0
    open_issues: int = 0
    language: str | None = None
    description: str | None = None
    default_branch: str = "main"
    last_push: str | None = None
    topics: list[str] = Field(default_factory=list)
