/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioUsernameRouteImport } from './routes/portfolio.$username'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSkillTreeRouteImport } from './routes/_app.skill-tree'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRepositoryQualityRouteImport } from './routes/_app.repository-quality'
import { Route as AppRecruiterRouteImport } from './routes/_app.recruiter'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileAnalyticsRouteImport } from './routes/_app.profile-analytics'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppPairProgrammingRouteImport } from './routes/_app.pair-programming'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNetworkingRouteImport } from './routes/_app.networking'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppLoadingStatesRouteImport } from './routes/_app.loading-states'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppHackathonsRouteImport } from './routes/_app.hackathons'
import { Route as AppHackathonDashboardRouteImport } from './routes/_app.hackathon-dashboard'
import { Route as AppGraphRouteImport } from './routes/_app.graph'
import { Route as AppFlaresRouteImport } from './routes/_app.flares'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppEnergyRouteImport } from './routes/_app.energy'
import { Route as AppDesignSystemRouteImport } from './routes/_app.design-system'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCodeReviewRouteImport } from './routes/_app.code-review'
import { Route as AppBuildersRouteImport } from './routes/_app.builders'
import { Route as AppBountiesRouteImport } from './routes/_app.bounties'
import { Route as AppBookmarksRouteImport } from './routes/_app.bookmarks'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app.organizations.index'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProfileUsernameRouteImport } from './routes/_app.profile.$username'
import { Route as AppOrganizationsOrgIdRouteImport } from './routes/_app.organizations.$orgId'
import { Route as AppMessagesConversationIdRouteImport } from './routes/_app.messages.$conversationId'
import { Route as AppHackathonsHackathonIdRouteImport } from './routes/_app.hackathons.$hackathonId'
import { Route as AppBuildersBuilderIdRouteImport } from './routes/_app.builders.$builderId'
import { Route as AppAdminSearchAnalyticsRouteImport } from './routes/_app.admin.search-analytics'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app.admin.notifications'
import { Route as AppAdminMaintenanceRouteImport } from './routes/_app.admin.maintenance'
import { Route as AppAdminJobsRouteImport } from './routes/_app.admin.jobs'
import { Route as AppAdminEmailTemplatesRouteImport } from './routes/_app.admin.email-templates'
import { Route as AppAdminCommunityStatsRouteImport } from './routes/_app.admin.community-stats'
import { Route as AppAdminAuditLogsRouteImport } from './routes/_app.admin.audit-logs'
import { Route as AppAdminApiRequestAnalyticsRouteImport } from './routes/_app.admin.api-request-analytics'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app.projects.$projectId.issues'
import { Route as AppProjectsProjectIdCollaborationMetricsRouteImport } from './routes/_app.projects.$projectId.collaboration-metrics'
import { Route as AppProjectsProjectIdActivityRouteImport } from './routes/_app.projects.$projectId.activity'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioUsernameRoute = PortfolioUsernameRouteImport.update({
  id: '/portfolio/$username',
  path: '/portfolio/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillTreeRoute = AppSkillTreeRouteImport.update({
  id: '/skill-tree',
  path: '/skill-tree',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryQualityRoute = AppRepositoryQualityRouteImport.update({
  id: '/repository-quality',
  path: '/repository-quality',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterRoute = AppRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileAnalyticsRoute = AppProfileAnalyticsRouteImport.update({
  id: '/profile-analytics',
  path: '/profile-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPairProgrammingRoute = AppPairProgrammingRouteImport.update({
  id: '/pair-programming',
  path: '/pair-programming',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkingRoute = AppNetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLoadingStatesRoute = AppLoadingStatesRouteImport.update({
  id: '/loading-states',
  path: '/loading-states',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHackathonsRoute = AppHackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => AppRoute,
} as any)
const AppHackathonDashboardRoute = AppHackathonDashboardRouteImport.update({
  id: '/hackathon-dashboard',
  path: '/hackathon-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppFlaresRoute = AppFlaresRouteImport.update({
  id: '/flares',
  path: '/flares',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergyRoute = AppEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeReviewRoute = AppCodeReviewRouteImport.update({
  id: '/code-review',
  path: '/code-review',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildersRoute = AppBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => AppRoute,
} as any)
const AppBountiesRoute = AppBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrgIdRoute = AppOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppMessagesConversationIdRoute =
  AppMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppMessagesRoute,
  } as any)
const AppHackathonsHackathonIdRoute =
  AppHackathonsHackathonIdRouteImport.update({
    id: '/$hackathonId',
    path: '/$hackathonId',
    getParentRoute: () => AppHackathonsRoute,
  } as any)
const AppBuildersBuilderIdRoute = AppBuildersBuilderIdRouteImport.update({
  id: '/$builderId',
  path: '/$builderId',
  getParentRoute: () => AppBuildersRoute,
} as any)
const AppAdminSearchAnalyticsRoute = AppAdminSearchAnalyticsRouteImport.update({
  id: '/search-analytics',
  path: '/search-analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMaintenanceRoute = AppAdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmailTemplatesRoute = AppAdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCommunityStatsRoute = AppAdminCommunityStatsRouteImport.update({
  id: '/community-stats',
  path: '/community-stats',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApiRequestAnalyticsRoute =
  AppAdminApiRequestAnalyticsRouteImport.update({
    id: '/api-request-analytics',
    path: '/api-request-analytics',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdCollaborationMetricsRoute =
  AppProjectsProjectIdCollaborationMetricsRouteImport.update({
    id: '/collaboration-metrics',
    path: '/collaboration-metrics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdActivityRoute =
  AppProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/bounties': typeof AppBountiesRoute
  '/builders': typeof AppBuildersRouteWithChildren
  '/code-review': typeof AppCodeReviewRoute
  '/dashboard': typeof AppDashboardRoute
  '/design-system': typeof AppDesignSystemRoute
  '/energy': typeof AppEnergyRoute
  '/feed': typeof AppFeedRoute
  '/flares': typeof AppFlaresRoute
  '/graph': typeof AppGraphRoute
  '/hackathon-dashboard': typeof AppHackathonDashboardRoute
  '/hackathons': typeof AppHackathonsRouteWithChildren
  '/insights': typeof AppInsightsRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/loading-states': typeof AppLoadingStatesRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/networking': typeof AppNetworkingRoute
  '/notifications': typeof AppNotificationsRoute
  '/organizations': typeof AppOrganizationsRouteWithChildren
  '/pair-programming': typeof AppPairProgrammingRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile-analytics': typeof AppProfileAnalyticsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/recruiter': typeof AppRecruiterRoute
  '/repository-quality': typeof AppRepositoryQualityRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/skill-tree': typeof AppSkillTreeRoute
  '/skills': typeof AppSkillsRoute
  '/templates': typeof AppTemplatesRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/admin/api-request-analytics': typeof AppAdminApiRequestAnalyticsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/community-stats': typeof AppAdminCommunityStatsRoute
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/maintenance': typeof AppAdminMaintenanceRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/search-analytics': typeof AppAdminSearchAnalyticsRoute
  '/builders/$builderId': typeof AppBuildersBuilderIdRoute
  '/hackathons/$hackathonId': typeof AppHackathonsHackathonIdRoute
  '/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/collaboration-metrics': typeof AppProjectsProjectIdCollaborationMetricsRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/bounties': typeof AppBountiesRoute
  '/builders': typeof AppBuildersRouteWithChildren
  '/code-review': typeof AppCodeReviewRoute
  '/dashboard': typeof AppDashboardRoute
  '/design-system': typeof AppDesignSystemRoute
  '/energy': typeof AppEnergyRoute
  '/feed': typeof AppFeedRoute
  '/flares': typeof AppFlaresRoute
  '/graph': typeof AppGraphRoute
  '/hackathon-dashboard': typeof AppHackathonDashboardRoute
  '/hackathons': typeof AppHackathonsRouteWithChildren
  '/insights': typeof AppInsightsRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/loading-states': typeof AppLoadingStatesRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/networking': typeof AppNetworkingRoute
  '/notifications': typeof AppNotificationsRoute
  '/pair-programming': typeof AppPairProgrammingRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile-analytics': typeof AppProfileAnalyticsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/recruiter': typeof AppRecruiterRoute
  '/repository-quality': typeof AppRepositoryQualityRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/skill-tree': typeof AppSkillTreeRoute
  '/skills': typeof AppSkillsRoute
  '/templates': typeof AppTemplatesRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/admin/api-request-analytics': typeof AppAdminApiRequestAnalyticsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/community-stats': typeof AppAdminCommunityStatsRoute
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/maintenance': typeof AppAdminMaintenanceRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/search-analytics': typeof AppAdminSearchAnalyticsRoute
  '/builders/$builderId': typeof AppBuildersBuilderIdRoute
  '/hackathons/$hackathonId': typeof AppHackathonsHackathonIdRoute
  '/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/collaboration-metrics': typeof AppProjectsProjectIdCollaborationMetricsRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/bounties': typeof AppBountiesRoute
  '/_app/builders': typeof AppBuildersRouteWithChildren
  '/_app/code-review': typeof AppCodeReviewRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/design-system': typeof AppDesignSystemRoute
  '/_app/energy': typeof AppEnergyRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/flares': typeof AppFlaresRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/hackathon-dashboard': typeof AppHackathonDashboardRoute
  '/_app/hackathons': typeof AppHackathonsRouteWithChildren
  '/_app/insights': typeof AppInsightsRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/loading-states': typeof AppLoadingStatesRoute
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/networking': typeof AppNetworkingRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/organizations': typeof AppOrganizationsRouteWithChildren
  '/_app/pair-programming': typeof AppPairProgrammingRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile-analytics': typeof AppProfileAnalyticsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/recruiter': typeof AppRecruiterRoute
  '/_app/repository-quality': typeof AppRepositoryQualityRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/skill-tree': typeof AppSkillTreeRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/_app/admin/api-request-analytics': typeof AppAdminApiRequestAnalyticsRoute
  '/_app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/_app/admin/community-stats': typeof AppAdminCommunityStatsRoute
  '/_app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/_app/admin/jobs': typeof AppAdminJobsRoute
  '/_app/admin/maintenance': typeof AppAdminMaintenanceRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/search-analytics': typeof AppAdminSearchAnalyticsRoute
  '/_app/builders/$builderId': typeof AppBuildersBuilderIdRoute
  '/_app/hackathons/$hackathonId': typeof AppHackathonsHackathonIdRoute
  '/_app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/_app/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/_app/projects/$projectId/collaboration-metrics': typeof AppProjectsProjectIdCollaborationMetricsRoute
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/forgot-password'
    | '/maintenance'
    | '/reset-password'
    | '/showcase'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/announcements'
    | '/bookmarks'
    | '/bounties'
    | '/builders'
    | '/code-review'
    | '/dashboard'
    | '/design-system'
    | '/energy'
    | '/feed'
    | '/flares'
    | '/graph'
    | '/hackathon-dashboard'
    | '/hackathons'
    | '/insights'
    | '/leaderboard'
    | '/loading-states'
    | '/messages'
    | '/networking'
    | '/notifications'
    | '/organizations'
    | '/pair-programming'
    | '/portfolio'
    | '/profile-analytics'
    | '/projects'
    | '/recruiter'
    | '/repository-quality'
    | '/search'
    | '/settings'
    | '/skill-tree'
    | '/skills'
    | '/templates'
    | '/portfolio/$username'
    | '/admin/api-request-analytics'
    | '/admin/audit-logs'
    | '/admin/community-stats'
    | '/admin/email-templates'
    | '/admin/jobs'
    | '/admin/maintenance'
    | '/admin/notifications'
    | '/admin/search-analytics'
    | '/builders/$builderId'
    | '/hackathons/$hackathonId'
    | '/messages/$conversationId'
    | '/organizations/$orgId'
    | '/profile/$username'
    | '/projects/$projectId'
    | '/settings/notifications'
    | '/organizations/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/collaboration-metrics'
    | '/projects/$projectId/issues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/forgot-password'
    | '/maintenance'
    | '/reset-password'
    | '/showcase'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/announcements'
    | '/bookmarks'
    | '/bounties'
    | '/builders'
    | '/code-review'
    | '/dashboard'
    | '/design-system'
    | '/energy'
    | '/feed'
    | '/flares'
    | '/graph'
    | '/hackathon-dashboard'
    | '/hackathons'
    | '/insights'
    | '/leaderboard'
    | '/loading-states'
    | '/messages'
    | '/networking'
    | '/notifications'
    | '/pair-programming'
    | '/portfolio'
    | '/profile-analytics'
    | '/projects'
    | '/recruiter'
    | '/repository-quality'
    | '/search'
    | '/settings'
    | '/skill-tree'
    | '/skills'
    | '/templates'
    | '/portfolio/$username'
    | '/admin/api-request-analytics'
    | '/admin/audit-logs'
    | '/admin/community-stats'
    | '/admin/email-templates'
    | '/admin/jobs'
    | '/admin/maintenance'
    | '/admin/notifications'
    | '/admin/search-analytics'
    | '/builders/$builderId'
    | '/hackathons/$hackathonId'
    | '/messages/$conversationId'
    | '/organizations/$orgId'
    | '/profile/$username'
    | '/projects/$projectId'
    | '/settings/notifications'
    | '/organizations'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/collaboration-metrics'
    | '/projects/$projectId/issues'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/avatar'
    | '/forgot-password'
    | '/maintenance'
    | '/reset-password'
    | '/showcase'
    | '/verify-email'
    | '/_app/admin'
    | '/_app/analytics'
    | '/_app/announcements'
    | '/_app/bookmarks'
    | '/_app/bounties'
    | '/_app/builders'
    | '/_app/code-review'
    | '/_app/dashboard'
    | '/_app/design-system'
    | '/_app/energy'
    | '/_app/feed'
    | '/_app/flares'
    | '/_app/graph'
    | '/_app/hackathon-dashboard'
    | '/_app/hackathons'
    | '/_app/insights'
    | '/_app/leaderboard'
    | '/_app/loading-states'
    | '/_app/messages'
    | '/_app/networking'
    | '/_app/notifications'
    | '/_app/organizations'
    | '/_app/pair-programming'
    | '/_app/portfolio'
    | '/_app/profile-analytics'
    | '/_app/projects'
    | '/_app/recruiter'
    | '/_app/repository-quality'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/skill-tree'
    | '/_app/skills'
    | '/_app/templates'
    | '/portfolio/$username'
    | '/_app/admin/api-request-analytics'
    | '/_app/admin/audit-logs'
    | '/_app/admin/community-stats'
    | '/_app/admin/email-templates'
    | '/_app/admin/jobs'
    | '/_app/admin/maintenance'
    | '/_app/admin/notifications'
    | '/_app/admin/search-analytics'
    | '/_app/builders/$builderId'
    | '/_app/hackathons/$hackathonId'
    | '/_app/messages/$conversationId'
    | '/_app/organizations/$orgId'
    | '/_app/profile/$username'
    | '/_app/projects/$projectId'
    | '/_app/settings/notifications'
    | '/_app/organizations/'
    | '/_app/projects/$projectId/activity'
    | '/_app/projects/$projectId/collaboration-metrics'
    | '/_app/projects/$projectId/issues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShowcaseRoute: typeof ShowcaseRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PortfolioUsernameRoute: typeof PortfolioUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$username': {
      id: '/portfolio/$username'
      path: '/portfolio/$username'
      fullPath: '/portfolio/$username'
      preLoaderRoute: typeof PortfolioUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skill-tree': {
      id: '/_app/skill-tree'
      path: '/skill-tree'
      fullPath: '/skill-tree'
      preLoaderRoute: typeof AppSkillTreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository-quality': {
      id: '/_app/repository-quality'
      path: '/repository-quality'
      fullPath: '/repository-quality'
      preLoaderRoute: typeof AppRepositoryQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter': {
      id: '/_app/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AppRecruiterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile-analytics': {
      id: '/_app/profile-analytics'
      path: '/profile-analytics'
      fullPath: '/profile-analytics'
      preLoaderRoute: typeof AppProfileAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pair-programming': {
      id: '/_app/pair-programming'
      path: '/pair-programming'
      fullPath: '/pair-programming'
      preLoaderRoute: typeof AppPairProgrammingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networking': {
      id: '/_app/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof AppNetworkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loading-states': {
      id: '/_app/loading-states'
      path: '/loading-states'
      fullPath: '/loading-states'
      preLoaderRoute: typeof AppLoadingStatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hackathons': {
      id: '/_app/hackathons'
      path: '/hackathons'
      fullPath: '/hackathons'
      preLoaderRoute: typeof AppHackathonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hackathon-dashboard': {
      id: '/_app/hackathon-dashboard'
      path: '/hackathon-dashboard'
      fullPath: '/hackathon-dashboard'
      preLoaderRoute: typeof AppHackathonDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flares': {
      id: '/_app/flares'
      path: '/flares'
      fullPath: '/flares'
      preLoaderRoute: typeof AppFlaresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/energy': {
      id: '/_app/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof AppEnergyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-system': {
      id: '/_app/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code-review': {
      id: '/_app/code-review'
      path: '/code-review'
      fullPath: '/code-review'
      preLoaderRoute: typeof AppCodeReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builders': {
      id: '/_app/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof AppBuildersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bounties': {
      id: '/_app/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof AppBountiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$orgId': {
      id: '/_app/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AppOrganizationsOrgIdRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/_app/messages/$conversationId': {
      id: '/_app/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AppMessagesConversationIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/hackathons/$hackathonId': {
      id: '/_app/hackathons/$hackathonId'
      path: '/$hackathonId'
      fullPath: '/hackathons/$hackathonId'
      preLoaderRoute: typeof AppHackathonsHackathonIdRouteImport
      parentRoute: typeof AppHackathonsRoute
    }
    '/_app/builders/$builderId': {
      id: '/_app/builders/$builderId'
      path: '/$builderId'
      fullPath: '/builders/$builderId'
      preLoaderRoute: typeof AppBuildersBuilderIdRouteImport
      parentRoute: typeof AppBuildersRoute
    }
    '/_app/admin/search-analytics': {
      id: '/_app/admin/search-analytics'
      path: '/search-analytics'
      fullPath: '/admin/search-analytics'
      preLoaderRoute: typeof AppAdminSearchAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/maintenance': {
      id: '/_app/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AppAdminMaintenanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/jobs': {
      id: '/_app/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/email-templates': {
      id: '/_app/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AppAdminEmailTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/community-stats': {
      id: '/_app/admin/community-stats'
      path: '/community-stats'
      fullPath: '/admin/community-stats'
      preLoaderRoute: typeof AppAdminCommunityStatsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit-logs': {
      id: '/_app/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/api-request-analytics': {
      id: '/_app/admin/api-request-analytics'
      path: '/api-request-analytics'
      fullPath: '/admin/api-request-analytics'
      preLoaderRoute: typeof AppAdminApiRequestAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/collaboration-metrics': {
      id: '/_app/projects/$projectId/collaboration-metrics'
      path: '/collaboration-metrics'
      fullPath: '/projects/$projectId/collaboration-metrics'
      preLoaderRoute: typeof AppProjectsProjectIdCollaborationMetricsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/activity': {
      id: '/_app/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof AppProjectsProjectIdActivityRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminApiRequestAnalyticsRoute: typeof AppAdminApiRequestAnalyticsRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminCommunityStatsRoute: typeof AppAdminCommunityStatsRoute
  AppAdminEmailTemplatesRoute: typeof AppAdminEmailTemplatesRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppAdminMaintenanceRoute: typeof AppAdminMaintenanceRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminSearchAnalyticsRoute: typeof AppAdminSearchAnalyticsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApiRequestAnalyticsRoute: AppAdminApiRequestAnalyticsRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminCommunityStatsRoute: AppAdminCommunityStatsRoute,
  AppAdminEmailTemplatesRoute: AppAdminEmailTemplatesRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppAdminMaintenanceRoute: AppAdminMaintenanceRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminSearchAnalyticsRoute: AppAdminSearchAnalyticsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppBuildersRouteChildren {
  AppBuildersBuilderIdRoute: typeof AppBuildersBuilderIdRoute
}

const AppBuildersRouteChildren: AppBuildersRouteChildren = {
  AppBuildersBuilderIdRoute: AppBuildersBuilderIdRoute,
}

const AppBuildersRouteWithChildren = AppBuildersRoute._addFileChildren(
  AppBuildersRouteChildren,
)

interface AppHackathonsRouteChildren {
  AppHackathonsHackathonIdRoute: typeof AppHackathonsHackathonIdRoute
}

const AppHackathonsRouteChildren: AppHackathonsRouteChildren = {
  AppHackathonsHackathonIdRoute: AppHackathonsHackathonIdRoute,
}

const AppHackathonsRouteWithChildren = AppHackathonsRoute._addFileChildren(
  AppHackathonsRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesConversationIdRoute: typeof AppMessagesConversationIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesConversationIdRoute: AppMessagesConversationIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppOrganizationsRouteChildren {
  AppOrganizationsOrgIdRoute: typeof AppOrganizationsOrgIdRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppOrganizationsRouteChildren: AppOrganizationsRouteChildren = {
  AppOrganizationsOrgIdRoute: AppOrganizationsOrgIdRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppOrganizationsRouteWithChildren =
  AppOrganizationsRoute._addFileChildren(AppOrganizationsRouteChildren)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdActivityRoute: typeof AppProjectsProjectIdActivityRoute
  AppProjectsProjectIdCollaborationMetricsRoute: typeof AppProjectsProjectIdCollaborationMetricsRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdActivityRoute: AppProjectsProjectIdActivityRoute,
  AppProjectsProjectIdCollaborationMetricsRoute:
    AppProjectsProjectIdCollaborationMetricsRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppBountiesRoute: typeof AppBountiesRoute
  AppBuildersRoute: typeof AppBuildersRouteWithChildren
  AppCodeReviewRoute: typeof AppCodeReviewRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppEnergyRoute: typeof AppEnergyRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFlaresRoute: typeof AppFlaresRoute
  AppGraphRoute: typeof AppGraphRoute
  AppHackathonDashboardRoute: typeof AppHackathonDashboardRoute
  AppHackathonsRoute: typeof AppHackathonsRouteWithChildren
  AppInsightsRoute: typeof AppInsightsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLoadingStatesRoute: typeof AppLoadingStatesRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppNetworkingRoute: typeof AppNetworkingRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRouteWithChildren
  AppPairProgrammingRoute: typeof AppPairProgrammingRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileAnalyticsRoute: typeof AppProfileAnalyticsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppRecruiterRoute: typeof AppRecruiterRoute
  AppRepositoryQualityRoute: typeof AppRepositoryQualityRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSkillTreeRoute: typeof AppSkillTreeRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppBountiesRoute: AppBountiesRoute,
  AppBuildersRoute: AppBuildersRouteWithChildren,
  AppCodeReviewRoute: AppCodeReviewRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppEnergyRoute: AppEnergyRoute,
  AppFeedRoute: AppFeedRoute,
  AppFlaresRoute: AppFlaresRoute,
  AppGraphRoute: AppGraphRoute,
  AppHackathonDashboardRoute: AppHackathonDashboardRoute,
  AppHackathonsRoute: AppHackathonsRouteWithChildren,
  AppInsightsRoute: AppInsightsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLoadingStatesRoute: AppLoadingStatesRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppNetworkingRoute: AppNetworkingRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationsRoute: AppOrganizationsRouteWithChildren,
  AppPairProgrammingRoute: AppPairProgrammingRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileAnalyticsRoute: AppProfileAnalyticsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppRecruiterRoute: AppRecruiterRoute,
  AppRepositoryQualityRoute: AppRepositoryQualityRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSkillTreeRoute: AppSkillTreeRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MaintenanceRoute: MaintenanceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShowcaseRoute: ShowcaseRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PortfolioUsernameRoute: PortfolioUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
